#!/usr/bin/env bash
# scripts/setup-baseline.sh — bring up the stock AI Town baseline (PLAN.md M0 §8).
#
# Idempotent: safe to re-run. Regenerates the admin key (it changes on every
# `docker compose down`), re-applies Convex env vars, and re-runs init.
set -euo pipefail

WIPE=0
[[ "${1:-}" == "--wipe" ]] && WIPE=1

cd "$(dirname "$0")/.."
ROOT=$(pwd)
[[ -f .env ]] || { echo "no .env — copy .env.example and set INSTANCE_SECRET" >&2; exit 1; }
set -a; . ./.env; set +a

CONVEX_URL="http://127.0.0.1:${CONVEX_PORT:-3210}"

echo "==> waiting for the Convex backend to be healthy"
until curl -fsS "$CONVEX_URL/version" >/dev/null 2>&1; do sleep 2; done
echo "    up: $(curl -fsS "$CONVEX_URL/version")"

echo "==> generating an admin key"
# Regenerated on every `down`/`up`, so always refresh it.
ADMIN_KEY=$(docker compose exec -T backend ./generate_admin_key.sh 2>/dev/null | tail -1 | tr -d '\r')
[[ -n "$ADMIN_KEY" ]] || { echo "failed to generate admin key" >&2; exit 1; }

cat > ai-town/.env.local <<EOL
# Generated by scripts/setup-baseline.sh — do not commit.
CONVEX_SELF_HOSTED_URL="$CONVEX_URL"
CONVEX_SELF_HOSTED_ADMIN_KEY="$ADMIN_KEY"
VITE_CONVEX_URL="$CONVEX_URL"
EOL
echo "    wrote ai-town/.env.local"

echo "==> pointing Convex at the LLM provider"
# Accept either spelling: LLM_API_KEY is what ai-town's custom provider reads,
# but OPENROUTER_API_KEY is the natural name to put in .env.
LLM_API_KEY="${AITOWN_LLM_API_KEY:-${OPENROUTER_API_KEY:-}}"
[[ -n "$LLM_API_KEY" ]] || { echo "set OPENROUTER_API_KEY in .env" >&2; exit 1; }
cd ai-town
# Clear any previous provider's vars: getLLMConfig auto-detects by which keys
# are present, so a leftover OLLAMA_*/OPENAI_* silently wins over LLM_API_URL.
for stale in OLLAMA_HOST OLLAMA_MODEL OLLAMA_EMBEDDING_MODEL OPENAI_API_KEY TOGETHER_API_KEY; do
    npx convex env remove "$stale" >/dev/null 2>&1 || true
done
# The repo .env namespaces these as AITOWN_* and we map them onto the names
# ai-town's getLLMConfig reads. They are NOT the same vars headlong uses: both
# systems define LLM_API_URL and mean different things by it -- ai-town treats
# it as a base and appends /v1/chat/completions, headlong uses it verbatim as
# the full endpoint. Headlong's thinkers read this repo's .env, so an unprefixed
# LLM_API_URL here silently points the minds at a web page. See PLAN.md §13.
for k in LLM_API_URL LLM_MODEL LLM_EMBEDDING_MODEL; do
    src="AITOWN_$k"
    npx convex env set "$k" "${!src:?}" >/dev/null
    echo "    $k=${!src}"
done
npx convex env set LLM_API_KEY "$LLM_API_KEY" >/dev/null
echo "    LLM_API_KEY=***"

if [[ "$WIPE" -eq 1 ]]; then
    # Required whenever the embedding model changes: the vector index dimension
    # must match the model, and existing rows carry the old dimension.
    echo "==> wiping all tables (--wipe)"
    npx convex run testing:wipeAllTables '{}' >/dev/null
fi

echo "==> deploying functions and seeding the world"
npm run predev

cat <<'EOL'

==> baseline is up. Now:
      cd ai-town && npm run dev:frontend     # the town, http://127.0.0.1:5173
      cd ai-town && npm run dev:backend      # deploy on change + tail logs
    dashboard: http://127.0.0.1:6791 (paste the admin key from ai-town/.env.local)
EOL
