#!/usr/bin/env bash
# scripts/setup-baseline.sh — bring up the stock AI Town baseline (PLAN.md M0 §8).
#
# Idempotent: safe to re-run. Regenerates the admin key (it changes on every
# `docker compose down`), re-applies Convex env vars, and re-runs init.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
[[ -f .env ]] || { echo "no .env — copy .env.example and set INSTANCE_SECRET" >&2; exit 1; }
set -a; . ./.env; set +a

CONVEX_URL="http://127.0.0.1:${CONVEX_PORT:-3210}"

echo "==> waiting for the Convex backend to be healthy"
until curl -fsS "$CONVEX_URL/version" >/dev/null 2>&1; do sleep 2; done
echo "    up: $(curl -fsS "$CONVEX_URL/version")"

echo "==> generating an admin key"
# Regenerated on every `down`/`up`, so always refresh it.
ADMIN_KEY=$(docker compose exec -T backend ./generate_admin_key.sh 2>/dev/null | tail -1 | tr -d '\r')
[[ -n "$ADMIN_KEY" ]] || { echo "failed to generate admin key" >&2; exit 1; }

cat > ai-town/.env.local <<EOL
# Generated by scripts/setup-baseline.sh — do not commit.
CONVEX_SELF_HOSTED_URL="$CONVEX_URL"
CONVEX_SELF_HOSTED_ADMIN_KEY="$ADMIN_KEY"
VITE_CONVEX_URL="$CONVEX_URL"
EOL
echo "    wrote ai-town/.env.local"

echo "==> pointing Convex at Ollama"
cd ai-town
for kv in "OLLAMA_HOST=${OLLAMA_HOST:?}" \
          "OLLAMA_MODEL=${OLLAMA_MODEL:?}" \
          "OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL:?}"; do
    npx convex env set "${kv%%=*}" "${kv#*=}" >/dev/null
    echo "    ${kv%%=*}=${kv#*=}"
done

echo "==> deploying functions and seeding the world"
npm run predev

cat <<'EOL'

==> baseline is up. Now:
      cd ai-town && npm run dev:frontend     # the town, http://127.0.0.1:5173
      cd ai-town && npm run dev:backend      # deploy on change + tail logs
    dashboard: http://127.0.0.1:6791 (paste the admin key from ai-town/.env.local)
EOL
